-- W0-T05 — the seed ledger.
--
-- Generated by `prisma migrate diff --from-empty --to-schema-datamodel`, so the DDL is exactly
-- what Prisma expects from the model and `migrate diff` reports no drift (AC12).

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE "_seed_run" (
    "id" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "ranAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "_seed_run_pkey" PRIMARY KEY ("id")
);
