/**
 * `W3-T01` — the category tree, as data.
 *
 * Two family roots and twenty leaves. This is the vocabulary a provider picks from, the list a
 * client searches by, and the column `W3-T08` reads as fact — so it ships as **curated seed data**
 * rather than behind an admin CRUD. §9 of the spec argues the difference: an endpoint that creates
 * a category at runtime makes `BD-07`'s legal answer editable by whoever holds an admin session,
 * which is the opposite of a legal boundary.
 *
 * **Not `localOnly`**, deliberately. `auth.demo-users` carries that flag because its rows have a
 * published password; nothing here is a credential or a person. A preview database should hold the
 * real taxonomy — it is the vocabulary the product is written in, not demo content — and since
 * `W3-T01` that is also what lets a preview deploy answer `GET /api/categories` with real rows
 * instead of the MSW handler this ticket deleted.
 *
 * Spec: `docs/specs/S3/W3-T01-category-tree.md` §3.5, §3.6, §8.3, §8.4.
 */
import { type Seeder } from './types.js';

/**
 * A node of the tree.
 *
 * `parent` is a **slug**, not an id: the roots' ids are generated by Postgres, and a seed constant
 * that had to know them would be a constant that cannot be read. `run` resolves them.
 */
export interface TaxonomyNode {
  /**
   * Fixed only for the four rows adopted from `demo-providers.ts` (§3.6). Everything else lets the
   * database generate one — `MEM-2026-09-18-1` fixes ids so a uuid in a screenshot still resolves,
   * and only the demo world has screenshots.
   */
  readonly id?: string;
  readonly slug: string;
  readonly nameEs: string;
  readonly nameEn: string;
  /** Per sibling set, 1..n. The curated order — the trades a marketplace wants first (§3.8). */
  readonly position: number;
  /**
   * **Declared on every row, never defaulted.** The operator ruled on 2026-09-18 (`BD-07`): five
   * `true`, fifteen `false`. A row whose answer had not arrived would not ship with `false`; it
   * would ship with the deferral spelled out, or not at all (§3.5).
   *
   * It marks a trade whose claim is **checkable and worth badging** — not one that hides unverified
   * providers. An electrician with no documents is listed, searchable and bookable; what they lack
   * is the badge (§3.5.2).
   */
  readonly requiresLicence: boolean;
  /** `null` for a family root. */
  readonly parent: string | null;
}

/** The four uuids `demo-providers.ts` created and this seeder adopts, so its links survive (§3.6). */
const adopted = (n: number): string =>
  `aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaa${String(n).padStart(4, '0')}`;

/**
 * The taxonomy. Roots first, because a child cannot be written before the row it points at.
 *
 * **`urgencias` is not here, and its absence is a decision** (§3.1). *Urgencia* is already two
 * things in this codebase — `EmergencyRequest` in the glossary, and `SearchUrgencySchema`'s frozen
 * `when` dimension since `W12-T08`. A third definition would be the only one a provider could
 * accidentally *be in*: `categories: ['fontaneria', 'urgencias']` is an availability claim inside a
 * column that means trade.
 *
 * **`fontaneria` is `false` beside three `true` rows**, which is worth reading twice. Plumbing as a
 * trade carries no national authorisation; the moment the work touches a gas appliance it is `gas`,
 * which does. That pair is the clearest instance of §3.5.1 in the table, and a reviewer who expects
 * plumbing to be regulated should find this note rather than file a bug.
 */
export const TAXONOMY: readonly TaxonomyNode[] = [
  // ── Roots ────────────────────────────────────────────────────────────────────────────────────
  // Never gated, and AC21 fails if one ever is: a licence attaches to the trade performed, not to
  // the umbrella above it (§3.5.1). Neither root is served on the wire (§3.2).
  { slug: 'reformas', nameEs: 'Reformas', nameEn: 'Renovations', position: 1, requiresLicence: false, parent: null },
  { slug: 'mantenimiento', nameEs: 'Mantenimiento', nameEn: 'Maintenance', position: 2, requiresLicence: false, parent: null },

  // ── Reformas ─────────────────────────────────────────────────────────────────────────────────
  // Every row `false`, which is the shape §3.5.1 predicts: this is where the wide, unregulated
  // build work lives, and the regulated parts of a renovation are gated through `mantenimiento`'s
  // trades when the provider claims them.
  //
  // `reforma-integral` is the largest thing on the list and is **not** gated. Marking it `true`
  // would demand a licence from a tiler and teach the column to mean "this job might involve
  // something regulated" — a guess about scope, not a legal boundary.
  { slug: 'reforma-integral', nameEs: 'Reforma integral', nameEn: 'Full renovation', position: 1, requiresLicence: false, parent: 'reformas' },
  { slug: 'albanileria', nameEs: 'Albañilería', nameEn: 'Masonry', position: 2, requiresLicence: false, parent: 'reformas' },
  { slug: 'alicatado-solados', nameEs: 'Alicatado y solados', nameEn: 'Tiling & flooring', position: 3, requiresLicence: false, parent: 'reformas' },
  { slug: 'pintura', nameEs: 'Pintura', nameEn: 'Painting', position: 4, requiresLicence: false, parent: 'reformas' },
  { slug: 'carpinteria', nameEs: 'Carpintería', nameEn: 'Carpentry', position: 5, requiresLicence: false, parent: 'reformas' },
  { slug: 'escayola-pladur', nameEs: 'Escayola y pladur', nameEn: 'Plasterboard', position: 6, requiresLicence: false, parent: 'reformas' },
  { slug: 'ventanas-cerramientos', nameEs: 'Ventanas y cerramientos', nameEn: 'Windows & glazing', position: 7, requiresLicence: false, parent: 'reformas' },
  { slug: 'aislamiento', nameEs: 'Aislamiento', nameEn: 'Insulation', position: 8, requiresLicence: false, parent: 'reformas' },

  // ── Mantenimiento ────────────────────────────────────────────────────────────────────────────
  { id: adopted(1), slug: 'fontaneria', nameEs: 'Fontanería', nameEn: 'Plumbing', position: 1, requiresLicence: false, parent: 'mantenimiento' },
  { id: adopted(2), slug: 'electricidad', nameEs: 'Electricidad', nameEn: 'Electrical', position: 2, requiresLicence: true, parent: 'mantenimiento' },
  { id: adopted(3), slug: 'cerrajeria', nameEs: 'Cerrajería', nameEn: 'Locksmith', position: 3, requiresLicence: false, parent: 'mantenimiento' },
  { id: adopted(4), slug: 'climatizacion', nameEs: 'Climatización', nameEn: 'Heating & cooling', position: 4, requiresLicence: true, parent: 'mantenimiento' },
  { slug: 'gas', nameEs: 'Instalaciones de gas', nameEn: 'Gas installations', position: 5, requiresLicence: true, parent: 'mantenimiento' },
  { slug: 'electrodomesticos', nameEs: 'Electrodomésticos', nameEn: 'Appliance repair', position: 6, requiresLicence: false, parent: 'mantenimiento' },
  { slug: 'telecomunicaciones', nameEs: 'Telecomunicaciones y antenas', nameEn: 'Telecoms & aerials', position: 7, requiresLicence: true, parent: 'mantenimiento' },
  { slug: 'placas-solares', nameEs: 'Placas solares', nameEn: 'Solar panels', position: 8, requiresLicence: true, parent: 'mantenimiento' },
  // `false`, and **provisional**: the operator is checking with the gremio. The risk is asymmetric —
  // `false` is the permissive answer, so being wrong surfaces an unlicensed provider, while being
  // wrong the other way only asks for a certificate nobody needed. One row and one AC20 line to
  // flip, and it is the operator's to chase (§10.1).
  { slug: 'desatascos', nameEs: 'Desatascos', nameEn: 'Drain unblocking', position: 9, requiresLicence: false, parent: 'mantenimiento' },
  { slug: 'limpieza', nameEs: 'Limpieza', nameEn: 'Cleaning', position: 10, requiresLicence: false, parent: 'mantenimiento' },
  { slug: 'jardineria', nameEs: 'Jardinería', nameEn: 'Gardening', position: 11, requiresLicence: false, parent: 'mantenimiento' },
  { slug: 'mudanzas', nameEs: 'Mudanzas y montaje', nameEn: 'Removals & assembly', position: 12, requiresLicence: false, parent: 'mantenimiento' },
];

export const categoryTaxonomy: Seeder = {
  id: 'categories.taxonomy',
  description:
    'Two family roots and twenty trades (W3-T01) — the vocabulary a provider picks from, with ' +
    "BD-07's five gated trades in requires_licence",

  /**
   * **`upsert`, not `create`.** `run.ts` runs each seeder once per database via its ledger, so a
   * plain `create` would be correct nearly always — and then collide with `category_slug_key` the
   * first time somebody re-runs this after a partial failure, or edits the taxonomy and wants the
   * rows brought up to date. The `update` half makes this a sync rather than an insert: change a
   * name or a position here, re-run, and the table follows (AC16).
   */
  async run({ db }) {
    const ids = new Map<string, string>();

    for (const node of TAXONOMY) {
      // Roots come first in `TAXONOMY`, so a parent is always already in the map. A slug that is
      // not names itself rather than writing `null` and quietly reparenting a trade to the root.
      let parentId: string | null = null;
      if (node.parent !== null) {
        const found = ids.get(node.parent);
        if (found === undefined) {
          throw new Error(`Category "${node.slug}" names a parent "${node.parent}" that is not seeded yet`);
        }
        parentId = found;
      }

      const fields = {
        nameEs: node.nameEs,
        nameEn: node.nameEn,
        parentId,
        requiresLicence: node.requiresLicence,
        position: node.position,
      };

      const row = await db.category.upsert({
        where: { slug: node.slug },
        create: { ...(node.id === undefined ? {} : { id: node.id }), slug: node.slug, ...fields, isActive: true },
        /**
         * **`isActive` is absent here, and that is the point.** It is the retirement mechanism
         * (§3.8, AC12): an operator sets it `false` to take a trade off the wire without touching
         * the `provider_category` rows that record who did it. If the update half carried
         * `isActive: true`, the next re-run of this seeder — after a typo fix, say — would put every
         * retired trade back on the public list, silently. Retirement is data, not taxonomy.
         */
        update: fields,
        select: { id: true },
      });

      ids.set(node.slug, row.id);
    }
  },
};
