/**
 * Human-readable content for every board issue, in user-story form.
 * Consumed by scripts/update-issues.ts to rewrite issue titles and bodies.
 * Keep the language plain: these are read by a person deciding what to do next.
 */
export type Story = {
  title: string; // human title, no ids — the script prefixes the id
  role: string; // who wants it
  want: string; // what they want
  so: string; // why it matters
  ac: string[]; // acceptance criteria, observable
  note?: string; // constraints worth knowing before starting
};

export const stories: Record<string, Story> = {
  // ---------------------------------------------------------------- OPS
  'OPS-01': {
    title: 'Authenticate the personal GitHub account on this machine',
    role: 'platform owner',
    want: 'my personal GitHub identity to be the one this repo uses',
    so: 'a private side project never ends up attributed to my employer',
    ac: [
      '`gh api user` returns the personal login',
      'commits are authored as mastrobardo@gmail.com',
      'the work account remains available but inactive for this repo',
    ],
    note: 'The SSH key on this machine still resolves to the work account, so this repo uses an HTTPS remote deliberately. See docs/board/IDENTITY.md.',
  },
  'OPS-02': {
    title: 'Create the GitHub repository and push main',
    role: 'platform owner',
    want: 'the code hosted under my personal account',
    so: 'CI, previews and the board have something to hang off',
    ac: ['repo exists and is private', '`main` pushed and tracking origin'],
  },
  'OPS-03': {
    title: 'Protect the main branch',
    role: 'reviewer',
    want: 'nobody — human or agent — to push straight to main',
    so: 'the quality gates cannot be bypassed by accident or in a hurry',
    ac: [
      'direct pushes to `main` rejected',
      'PR requires at least one approval',
      'required status checks must pass before merge',
    ],
  },
  'OPS-04': {
    title: 'Create the preview, staging and production environments',
    role: 'developer',
    want: 'three named environments with their own secrets',
    so: 'a preview can never reach production credentials',
    ac: [
      '`preview`, `staging`, `production` exist in repo settings',
      'each has its own secret set, none shared',
      'production requires manual approval to deploy',
    ],
  },
  'OPS-05': {
    title: 'Set up the project board and import the issues',
    role: 'platform owner',
    want: 'one board where I can see what is in flight and what is waiting on me',
    so: 'planning happens in one place instead of across a 135-row issue list',
    ac: [
      'project board exists with saved views: Do now, Waiting on me, Manual setup',
      'every issue is on the board',
      'board groups by milestone',
    ],
    note: 'Creating the board needs the `project` token scope: `gh auth refresh -s project`.',
  },
  'OPS-06': {
    title: 'Decide on the GitHub MCP connection',
    role: 'platform owner',
    want: 'to choose between the gh CLI and a stored PAT for agent GitHub access',
    so: 'I am not keeping a long-lived credential in a plaintext config without a reason',
    ac: [
      'a decision is recorded',
      'if MCP is adopted, the token is personal and scoped as narrowly as possible',
    ],
    note: 'Not needed for the walking skeleton. Revisit only if agents start needing GitHub access from CI.',
  },
  'OPS-07': {
    title: 'Create the Neon databases (staging and production)',
    role: 'developer',
    want: 'a managed Postgres with branching, and production isolated from everything else',
    so: 'each pull request gets a throwaway database and real customer data can never be branched into one',
    ac: [
      'staging project created with PostGIS enabled',
      'production is a SEPARATE project, not a branch',
      'connection strings stored per environment',
      'connections require `sslmode=verify-full`',
    ],
    note: 'The separation is deliberate: it makes leaking production data into a preview structurally impossible.',
  },
  'OPS-08': {
    title: 'Create the Fly.io account and deploy token',
    role: 'developer',
    want: 'somewhere to run the API that bills per second and scales to zero',
    so: 'an idle preview environment costs cents rather than a monthly fee',
    ac: ['org created', 'API token stored in CI secrets', '`fly apps list` works from CI'],
    note: 'No Spain region exists — Paris is nearest, roughly 25ms from Madrid.',
  },
  'OPS-09': {
    title: 'Set up Cloudflare Pages and the R2 bucket',
    role: 'developer',
    want: 'free per-branch preview URLs for the frontend and cheap private file storage',
    so: 'every pull request is clickable and image bandwidth does not become a bill',
    ac: [
      'Pages project connected to the repo',
      'R2 bucket created and PRIVATE',
      'API token stored in CI secrets',
    ],
    note: 'Free tier allows unlimited previews but only one concurrent build — watch for queueing.',
  },
  'OPS-10': {
    title: 'Set up Flagsmith with one environment per deployment target',
    role: 'developer',
    want: 'to turn a feature on in staging while it stays off in production',
    so: 'unfinished work can merge to main without blocking anyone',
    ac: [
      'project created',
      '`preview`, `staging`, `production` environments exist',
      'SDK keys stored per environment',
    ],
    note: 'Not needed for the walking skeleton — set this up with `W0-T17`, when the first feature actually needs a flag.',
  },
  'OPS-11': {
    title: 'Create the Sentry project',
    role: 'developer',
    want: 'errors to arrive somewhere I will actually look',
    so: 'a broken preview is noticed before someone else trips over it',
    ac: [
      'project created',
      'DSN stored per environment',
      'a test event is visible in the dashboard',
    ],
  },
  'OPS-12': {
    title: 'Create the Google Maps API key with billing limits',
    role: 'developer',
    want: 'address autocomplete and a map, with a hard spending ceiling',
    so: 'a bug in a loop cannot generate a four-figure bill overnight',
    ac: [
      'key created and restricted by referrer/IP',
      'billing alerts and a quota cap configured',
      'only the APIs we use are enabled',
    ],
    note: 'Not needed for the walking skeleton — set this up with `W3-T06`, when the map and address search are built.',
  },
  'OPS-13': {
    title: 'Set up the Stripe test account with Connect',
    role: 'developer',
    want: 'a sandbox where providers can onboard and payments can be tested end to end',
    so: 'the money flow is proven long before real money touches it',
    ac: [
      'Connect Express enabled and branded',
      'webhook endpoint registered for staging',
      'a test PaymentIntent succeeds',
      'test-mode keys stored per environment',
    ],
    note: 'Not needed for the walking skeleton — set this up with `W5-T01`, when provider payouts are built.',
  },
  'OPS-14': {
    title: 'Set up the transactional email provider',
    role: 'client',
    want: 'to receive verification and booking emails reliably',
    so: 'I can actually complete signup and know what is happening with my job',
    ac: [
      'sender domain verified (SPF/DKIM)',
      'test email delivered to a real inbox',
      'API key stored per environment',
    ],
    note: 'Not needed for the walking skeleton — set this up with `W2-T01`, when signup needs to send a verification email. MailHog covers local development until then.',
  },
  'OPS-15': {
    title: 'Set up the SMS provider with a Spanish sender',
    role: 'professional',
    want: 'to be reachable by SMS for phone verification and emergency call-outs',
    so: 'urgent work reaches me even when I do not have the app open',
    ac: [
      'Spanish sender configured',
      'test SMS delivered to a Spanish number',
      'per-message cost recorded for budgeting',
    ],
    note: 'Not needed for the walking skeleton — set this up with `W2-T06`, when phone verification is built.',
  },
  'OPS-16': {
    title: 'Point the domain and DNS at Cloudflare',
    role: 'platform owner',
    want: 'a real hostname for staging and, later, production',
    so: 'the product can be shown to people without sending them a random preview URL',
    ac: ['domain registered', 'DNS on Cloudflare', 'staging hostname resolves over HTTPS'],
    note: 'Not needed for the walking skeleton — the fly.dev and pages.dev URLs are enough. Do this before showing staging to anyone outside the project.',
  },
  'OPS-17': {
    title: 'Generate and store the per-environment encryption keys',
    role: 'platform owner',
    want: 'each environment to hold its own data-encryption key',
    so: 'a leak in one environment cannot decrypt another environment’s data',
    ac: [
      'a distinct key per environment',
      'keys stored in the secret store only — never in the repo',
      'a key-rotation procedure written down',
    ],
    note: 'Not needed for the walking skeleton — set this up with `W0-T18`, when the first sensitive field is actually stored.',
  },
  'OPS-18': {
    title: 'Activate the live Stripe account (before launch only)',
    role: 'platform owner',
    want: 'the real payment account with KYC and bank details completed',
    so: 'we can take actual money at beta launch',
    ac: [
      'business verification complete',
      'bank account connected',
      'live keys stored in production only',
    ],
    note: 'Do not start this before M9.',
  },

  // ---------------------------------------------------------- BUSINESS DECISIONS
  'BD-01': {
    title: 'Decide: do we hold client money until the job is finished?',
    role: 'platform owner',
    want: 'to decide whether the platform holds funds between payment and completion',
    so: 'the payment code, the legal position and the client’s protection all follow from this one answer',
    ac: [
      'a decision is recorded with its reasoning',
      'if yes: manual capture + delayed transfer, and a legal review is booked before M8',
      'if no: the client pays the professional on completion and we take a fee at that moment',
    ],
    note: 'The keystone decision. Holding funds is what makes clients feel safe and what makes lawyers nervous — it may make us a payment intermediary under Spanish/EU rules. Everything in the money slice waits on this.',
  },
  'BD-02': {
    title: 'Decide the platform commission',
    role: 'platform owner',
    want: 'to set what we take from each job, and whether subscribers pay less',
    so: 'the business has unit economics and the subscription has a reason to exist',
    ac: [
      'a percentage (or fee structure) is chosen',
      'whether subscribers get a reduced rate is decided',
      'who sees the fee — client, professional, or both — is decided',
    ],
  },
  'BD-03': {
    title: 'Decide what PLUS and PREMIUM actually buy',
    role: 'professional',
    want: 'to understand what I get for paying a monthly fee',
    so: 'the subscription is worth buying and I am not paying for a badge alone',
    ac: [
      'each tier’s entitlements are listed (quote volume, service radius, ranking, badge, lead priority)',
      'monthly price per tier is set',
      'whether paying boosts search ranking is decided explicitly',
    ],
    note: 'Ranking boost has a fairness cost — a paying but poorly-rated professional outranking a good one damages trust. Decide it deliberately rather than by default.',
  },
  'BD-04': {
    title: 'Decide the cancellation and refund policy',
    role: 'client',
    want: 'to know what happens to my money if I cancel, and when',
    so: 'I book with confidence instead of worrying about being trapped',
    ac: [
      'time-based refund bands defined (e.g. free until 24h before)',
      'what the professional receives on a late cancellation is decided',
      'who absorbs the payment-processing fee is decided',
    ],
  },
  'BD-05': {
    title: 'Decide how emergency call-outs are priced',
    role: 'client',
    want: 'to know what an urgent visit will cost before I request one',
    so: 'I am not surprised by the bill during an already stressful situation',
    ac: [
      'pricing model chosen: call-out fee plus hourly, or a multiplier on normal rates',
      'whether the professional sets it or the platform does is decided',
      'what the client sees before confirming is defined',
    ],
  },
  'BD-06': {
    title: 'Decide whether manitas need any verification',
    role: 'client',
    want: 'to know that the person I let into my home has been checked in some way',
    so: 'I trust the platform enough to use it for the first time',
    ac: [
      'whether non-licensed providers need an ID check is decided',
      'if yes, what document and who reviews it',
      'the trade-off against supply-side signup friction is acknowledged',
    ],
    note: 'More checking means more trust but fewer providers at launch — and we already have a cold-start problem.',
  },
  'BD-07': {
    title: 'Decide which job categories legally require a licence in Spain',
    role: 'platform owner',
    want: 'a definitive list of the work only certified professionals may do',
    so: 'we do not connect a client with someone unqualified for gas or electrical work',
    ac: [
      'category list produced with a licence flag on each',
      'the source (regulation or professional body) is cited for each flagged category',
    ],
    note: 'This is a legal boundary, not a product preference. Worth confirming with someone who knows Spanish trade regulation.',
  },
  'BD-08': {
    title: 'Decide how hard we work to keep jobs on the platform',
    role: 'platform owner',
    want: 'to set how aggressively contact details are hidden before payment',
    so: 'we earn from the matches we make without making the product annoying to use',
    ac: [
      'what is masked, and until when, is decided',
      'what happens if users share contact details anyway is decided',
    ],
    note: 'Too strict and people find it obstructive; too loose and we do the matching for free.',
  },
  'BD-09': {
    title: 'Decide the auction rules',
    role: 'professional',
    want: 'auctions with rules that reward doing good work rather than gaming the clock',
    so: 'bidding is worth my time',
    ac: [
      'sealed or open bidding chosen as the default',
      'anti-sniping window decided (extend the deadline on a late bid?)',
      'how many bids each subscription tier allows',
    ],
  },
  'BD-10': {
    title: 'Decide what earns a badge and when ratings are shown',
    role: 'client',
    want: 'badges and star ratings that actually mean something',
    so: 'I can tell a genuinely good professional from a new one',
    ac: [
      'qualifying rules for TOP_RATED and FAST_RESPONDER defined',
      'minimum number of reviews before an average is displayed',
      'whether badges expire is decided',
    ],
  },
  'BD-11': {
    title: 'Decide the support impersonation policy',
    role: 'client',
    want: 'to know when support can see the platform as me, and to have it recorded',
    so: 'my privacy is respected while my problem still gets solved',
    ac: [
      'whether impersonation is allowed at all is decided',
      'if allowed: consent, time limit, and what the user sees afterwards',
      'audit requirements defined',
    ],
    note: 'GDPR-sensitive. Building it without a decision would be the wrong order.',
  },
  'BD-12': {
    title: 'Choose the launch city or region',
    role: 'platform owner',
    want: 'one geographic area to launch in',
    so: 'we can concentrate enough professionals in one place for the marketplace to actually work',
    ac: [
      'a city or region chosen',
      'a target number of professionals before opening to clients',
      'demo/seed data reflects that area',
    ],
    note: 'Marketplaces die from being thinly spread. One neighbourhood that works beats a country that does not.',
  },
  'BD-13': {
    title: 'Establish the invoicing and tax rules',
    role: 'professional',
    want: 'correct invoices for the work I do through the platform',
    so: 'I can meet my obligations as an autónomo without extra bookkeeping',
    ac: [
      'who issues the invoice — platform or professional — is decided',
      'IVA treatment of the job and of our commission is confirmed',
      'platform reporting duties (DAC7) are understood',
    ],
    note: 'Needs an accountant. Do not let this be inferred from code.',
  },
  'BD-14': {
    title: 'Decide how long we keep data',
    role: 'client',
    want: 'my data deleted when it is no longer needed',
    so: 'the platform respects my rights and stays lawful',
    ac: [
      'retention period per data type (account, job, message, licence, payment record)',
      'what deletion actually removes versus anonymises',
      'how long licence documents are kept after a professional leaves',
    ],
  },

  // ---------------------------------------------------------------- W0 platform
  'W0-T01': {
    title: 'Set up the monorepo skeleton',
    role: 'developer',
    want: 'one repo holding the API, the web app and the shared packages',
    so: 'agents can work on different parts without fighting over tooling',
    ac: [
      'pnpm workspaces resolve across apps and packages',
      'shared TypeScript, lint and format config in one place',
      'a single command installs everything',
    ],
  },
  'W0-T02': {
    title: 'Run the local stack with one command',
    role: 'developer',
    want: 'Postgres with PostGIS, a mail catcher and object storage running locally',
    so: 'I can develop and test without touching a paid service',
    ac: [
      '`docker compose up` gives a working database with PostGIS',
      'emails are caught locally instead of sent',
      'S3-compatible storage available for uploads',
    ],
  },
  'W0-T03': {
    title: 'Create the API skeleton',
    role: 'developer',
    want: 'a running Fastify server with health, config, logging and error handling',
    so: 'every feature is built on the same foundation instead of inventing its own',
    ac: [
      'health endpoint responds',
      'config fails loudly at boot if a required variable is missing',
      'every request has a trace id in its log line',
      'errors return the shared envelope with a machine-readable code',
    ],
  },
  'W0-T04': {
    title: 'Create the web app skeleton',
    role: 'developer',
    want: 'a running React app with routing, layout, translations and theme tokens',
    so: 'features are dropped into a real shell rather than assembled ad hoc',
    ac: [
      'routing and a page shell work',
      'Spanish and English both resolve',
      'a missing translation key fails the build rather than showing the key',
    ],
  },
  'W0-T05': {
    title: 'Set up the database toolchain',
    role: 'developer',
    want: 'migrations and a seed script wired up from the start',
    so: 'schema changes are versioned and every environment can be filled with sensible data',
    ac: [
      'first migration applies cleanly to an empty database',
      'seed script runs and is repeatable',
      'migrations are reversible',
    ],
  },
  'W0-T06': {
    title: 'Run checks automatically on every pull request',
    role: 'reviewer',
    want: 'types, lint, tests and builds checked before I look at a change',
    so: 'review time is spent on judgement rather than catching typos',
    ac: [
      'all checks run on every PR',
      'a failing check blocks merge',
      'the PR path finishes in under about ten minutes',
    ],
  },
  'W0-T07': {
    title: 'Give every pull request its own deployed environment',
    role: 'reviewer',
    want: 'a clickable URL for each PR, and main deployed to staging automatically',
    so: 'we judge changes by using them instead of imagining them',
    ac: [
      'opening a PR deploys an API and a web preview',
      'the preview is destroyed when the PR closes',
      'merging to main updates staging',
      'production deploys only from a manual, tagged release',
    ],
  },
  'W0-T08': {
    title: 'Make failures visible',
    role: 'developer',
    want: 'errors, uptime and structured logs collected somewhere I can search',
    so: 'a problem in staging is diagnosed instead of guessed at',
    ac: [
      'errors reach Sentry with the trace id attached',
      'an uptime check alerts when staging is down',
      'logs are structured and searchable',
    ],
  },
  'W0-T09': {
    title: 'Populate the secrets for every environment',
    role: 'platform owner',
    want: 'each environment holding exactly the credentials it needs',
    so: 'nothing runs with a missing key and no environment can use another’s credentials',
    ac: [
      'every variable in `.env.example` has a real value in each environment',
      'no secret appears in the repository or in logs',
    ],
    note: 'Human-only by rule: agents maintain the example file, never the values.',
  },
  'W0-T10': {
    title: 'Write the contributor guide for agents',
    role: 'developer',
    want: 'the working agreement as a checklist I can follow',
    so: 'a new agent behaves correctly on its first task without being told',
    ac: [
      'the pipeline, gates and definition of done are written as steps',
      'it matches agents/AGENTS.md rather than duplicating it loosely',
    ],
  },
  'W0-T11': {
    title: 'Build the agent instruction set',
    role: 'developer',
    want: 'system-wide rules, per-agent charters and prompt templates in the repo',
    so: 'every agent boots with the same rules and the same idea of done',
    ac: [
      'AGENTS.md, policies, prompts and role charters exist',
      'Claude Code subagents are generated from the charters, not hand-written',
    ],
  },
  'W0-T12': {
    title: 'Require a spec and an intervention record before merge',
    role: 'reviewer',
    want: 'CI to reject a branch with no spec, and any human-corrected PR with no record of it',
    so: 'we can see how the work was produced and where agents went wrong',
    ac: [
      'a task branch without a spec and run record fails CI',
      'a PR labelled as a human intervention fails without a ledger entry',
      'the PR template asks whether a human changed anything',
    ],
  },
  'W0-T13': {
    title: 'Turn on branch protection',
    role: 'reviewer',
    want: 'main to be reachable only through a reviewed, passing PR',
    so: 'the gates we built cannot be walked around',
    ac: ['direct pushes blocked', 'required checks configured', 'at least one approval required'],
  },
  'W0-T14': {
    title: 'Build the agent memory structure',
    role: 'developer',
    want: 'somewhere durable for what agents learn, separate from per-session notes',
    so: 'an agent starting a new session does not rediscover what another already knew',
    ac: [
      'long-term repo and per-slice memory files exist',
      'session files carry a handoff block',
      'the promotion path from session to long-term is documented',
    ],
  },
  'W0-T15': {
    title: 'Keep generated agent files in sync',
    role: 'reviewer',
    want: 'CI to fail if the generated subagent files drift from their source charters',
    so: 'there is exactly one source of truth for how an agent behaves',
    ac: ['a drift check runs in CI', 'regenerating produces no diff on a clean branch'],
  },
  'W0-T16': {
    title: 'Give every pull request its own database',
    role: 'developer',
    want: 'a fresh database branch per PR, created from sanitised staging data',
    so: 'two agents testing at once never corrupt each other’s data',
    ac: [
      'opening a PR creates a database branch',
      'closing the PR deletes it',
      'the branch is created from sanitised data, never production',
      'connections verify the server certificate',
    ],
  },
  'W0-T17': {
    title: 'Put every feature behind a switch',
    role: 'developer',
    want: 'to merge unfinished work with its feature turned off everywhere but its own preview',
    so: 'nobody is blocked waiting for someone else’s branch to be finished',
    ac: [
      'flags are declared in code with an owner and a removal task',
      'a new flag defaults to off',
      'flags resolve differently per environment',
      'the server resolves flags and passes them to the client — no per-request calls',
      'tests use a fixed flag set, never the network',
    ],
  },
  'W0-T18': {
    title: 'Encrypt the sensitive fields',
    role: 'client',
    want: 'my licence details and phone number encrypted beyond the database’s own encryption',
    so: 'a database leak alone does not expose them',
    ac: [
      'sensitive columns encrypted with a per-environment key',
      'lookup fields use a keyed hash so search still works',
      'keys live only in the secret store',
      'a rotation procedure is written down',
    ],
  },
  'W0-T19': {
    title: 'Set up the project board',
    role: 'platform owner',
    want: 'the work visible as a board with useful views',
    so: 'I can see what to do now and what is waiting on my decision',
    ac: [
      'every task is an issue with slice, owner and execution labels',
      'saved views for “do now”, “waiting on me” and “manual setup”',
      'issues grouped under epics',
    ],
  },
  'W0-T20': {
    title: 'Strip personal data out of preview databases',
    role: 'client',
    want: 'my data never copied into a temporary test environment',
    so: 'a throwaway preview cannot leak real people’s addresses or licence documents',
    ac: [
      'the sanitisation step removes or fakes all personal data and document references',
      'preview branches are created only from sanitised data',
      'a test proves no real record survives',
    ],
  },
  'W0-T21': {
    title: 'Reject commits made with the wrong identity',
    role: 'platform owner',
    want: 'CI to fail if any commit was authored by my work account',
    so: 'personal and work identities never get mixed in this repo',
    ac: [
      'every commit author and committer on a PR is checked',
      'a wrong identity fails the build with a clear message',
    ],
  },
  'W0-T22': {
    title: 'Generate the board from the plan',
    role: 'platform owner',
    want: 'issues created automatically from TODO.md',
    so: 'the plan and the board cannot drift apart by hand',
    ac: [
      'one issue per task with labels and milestone',
      'rerunning skips issues that already exist',
      'it refuses to run under the wrong GitHub account',
    ],
  },

  // ---------------------------------------------------------------- W1 contracts
  'W1-T01': {
    title: 'Agree one shape for every error',
    role: 'developer',
    want: 'all API errors returned in the same envelope with a stable code',
    so: 'the frontend can react to failures instead of showing a generic message',
    ac: [
      'one error shape used everywhere',
      'each error has a machine-readable code and an HTTP status',
      'no internal detail leaks in the message',
    ],
  },
  'W1-T02': {
    title: 'Agree how lists are paged, sorted and filtered',
    role: 'developer',
    want: 'one convention for every list endpoint',
    so: 'each new endpoint does not invent its own and the client can be generic',
    ac: [
      'paging, sorting and filtering conventions documented and applied',
      'limits are enforced so a client cannot request everything',
    ],
  },
  'W1-T03': {
    title: 'Generate the API client from the schemas',
    role: 'developer',
    want: 'the typed client and API documentation produced from one definition',
    so: 'the frontend and backend cannot drift apart',
    ac: [
      'schemas produce OpenAPI and a typed client',
      'the generated client is never hand-edited',
      'regeneration produces no diff when nothing changed',
    ],
  },
  'W1-T04': {
    title: 'Prove the API matches its own documentation',
    role: 'reviewer',
    want: 'a test that compares every live route against the published contract',
    so: 'documentation cannot quietly become fiction',
    ac: ['every route is checked against the contract in CI', 'a mismatch fails the build'],
  },
  'W1-T05': {
    title: 'Create the core database schema',
    role: 'developer',
    want: 'users, profiles, categories and location columns in place',
    so: 'every slice builds on the same foundation instead of inventing its own tables',
    ac: [
      'core models migrated',
      'location columns indexed for proximity search',
      'names match the agreed glossary',
    ],
  },
  'W1-T06': {
    title: 'Handle money safely',
    role: 'platform owner',
    want: 'all amounts stored and calculated as whole cents',
    so: 'rounding errors never turn into reconciliation problems',
    ac: [
      'a shared money type with currency',
      'rounding rules defined and tested',
      'no floating point anywhere near an amount',
    ],
  },
  'W1-T07': {
    title: 'Make state changes consistent and traceable',
    role: 'reviewer',
    want: 'one mechanism for moving anything between states',
    so: 'every transition is guarded and recorded rather than assigned ad hoc',
    ac: [
      'transitions declared as a table with guards',
      'an invalid transition is rejected',
      'every transition writes an audit record',
    ],
  },
  'W1-T08': {
    title: 'Record the founding decisions',
    role: 'developer',
    want: 'the stack, contract, money, geography and auth decisions written down with their reasoning',
    so: 'nobody reopens a settled question without knowing why it was settled',
    ac: [
      'a decision record template exists',
      'the first five decisions are recorded with context and consequences',
    ],
  },
  'W1-T09': {
    title: 'Provide shared test data builders',
    role: 'developer',
    want: 'one place to build users, providers, jobs and bookings for tests',
    so: 'every agent tests against the same shapes and failures are reproducible',
    ac: [
      'factories cover the core entities',
      'the seed is deterministic',
      'tests do not hand-roll their own fixtures',
    ],
  },

  // ---------------------------------------------------------------- W2 identity
  'W2-T01': {
    title: 'Let people sign up and sign in',
    role: 'client',
    want: 'to create an account with my email and get back into it later',
    so: 'I can use the platform at all',
    ac: [
      'signup, email verification, login and password reset all work',
      'passwords are stored hashed with a modern algorithm',
      'an unknown email and a wrong password are indistinguishable in response and timing',
    ],
  },
  'W2-T02': {
    title: 'Keep people signed in safely',
    role: 'client',
    want: 'to stay logged in without leaving my account open to theft',
    so: 'convenience does not cost me my account',
    ac: [
      'short-lived access token with a refresh cookie that rotates',
      'logging out actually revokes the session',
      'a stolen token expires quickly',
    ],
  },
  'W2-T03': {
    title: 'Enforce what each role may do',
    role: 'platform owner',
    want: 'a written permissions matrix enforced on every endpoint',
    so: 'a client cannot act as a professional and nobody can act as an admin',
    ac: [
      'permissions matrix documented',
      'every endpoint checks it',
      'every denial has a test — not just the happy path',
    ],
  },
  'W2-T04': {
    title: 'Let clients manage their details and addresses',
    role: 'client',
    want: 'to save my address so I do not retype it for every job',
    so: 'posting a second job is quick',
    ac: [
      'profile and multiple addresses can be created, edited and removed',
      'a default location can be set',
    ],
  },
  'W2-T05': {
    title: 'Let providers sign up as a manitas or a professional',
    role: 'professional',
    want: 'a signup that asks for what my type of work actually requires',
    so: 'I am not asked for a licence I do not need, or allowed to skip one I do',
    ac: [
      'the two paths ask for different information',
      'the choice is recorded on the profile',
      'licensed categories stay locked until verification',
    ],
  },
  'W2-T06': {
    title: 'Verify provider phone numbers',
    role: 'client',
    want: 'the professionals on the platform to have a confirmed phone number',
    so: 'someone coming to my home is at least contactable and traceable',
    ac: [
      'a code is sent and checked',
      'an unverified provider cannot receive work',
      'resend attempts are rate limited',
    ],
  },
  'W2-T07': {
    title: 'Defend the login endpoints',
    role: 'platform owner',
    want: 'rate limiting, lockout and an audit trail on authentication',
    so: 'automated attacks fail and we can see when they happened',
    ac: [
      'repeated failures are throttled then locked out',
      'auth events are recorded with enough detail to investigate',
    ],
  },
  'W2-T08': {
    title: 'Let people export and delete their data',
    role: 'client',
    want: 'to take my data with me or have it removed',
    so: 'my legal rights are respected',
    ac: [
      'export returns everything held about the account',
      'deletion anonymises rather than breaking bookings and financial records',
      'retention rules are applied',
    ],
  },

  // ---------------------------------------------------------------- W3 providers & discovery
  'W3-T01': {
    title: 'Define the service categories',
    role: 'client',
    want: 'to pick the kind of work I need from a clear list',
    so: 'I reach the right professionals instead of describing my problem into a void',
    ac: [
      'category tree covers renovation, maintenance and emergencies',
      'each category records whether it legally requires a licence',
      'names exist in Spanish and English',
    ],
  },
  'W3-T02': {
    title: 'Let providers describe their work and coverage',
    role: 'professional',
    want: 'to say what I do, where I travel and what I charge',
    so: 'I appear in the right searches and get relevant enquiries',
    ac: [
      'categories, travel radius, rates and working hours can be set',
      'incomplete profiles are not shown in search',
    ],
  },
  'W3-T03': {
    title: 'Let providers show past work',
    role: 'professional',
    want: 'to upload photos of jobs I have completed',
    so: 'clients can see the quality of my work before hiring me',
    ac: [
      'images upload and can be reordered',
      'location data is stripped from every photo',
      'only allowed file types and sizes are accepted',
    ],
  },
  'W3-T04': {
    title: 'Let providers publish what they offer',
    role: 'professional',
    want: 'to list a service with a fixed price, an hourly rate, or quote-only',
    so: 'clients understand what they are buying before contacting me',
    ac: [
      'listings can be created, edited, deactivated',
      'each price model displays correctly',
      'prices are stored as whole cents',
    ],
  },
  'W3-T05': {
    title: 'Find providers near an address',
    role: 'client',
    want: 'to search for professionals near me and filter the results',
    so: 'I find someone who can actually come to my home',
    ac: [
      'search by location and radius returns nearby providers',
      'filters for category, price, rating and availability work together',
      'results are paged and fast enough under load',
      'proximity is calculated in the database, not by an external service',
    ],
  },
  'W3-T06': {
    title: 'Show results as a list and a map',
    role: 'client',
    want: 'to see who is nearby on a map, on my phone',
    so: 'I can judge distance at a glance',
    ac: [
      'list and map show the same results',
      'the map clusters when zoomed out',
      'it works on a small screen',
      'a provider’s exact home address is never revealed',
    ],
  },
  'W3-T07': {
    title: 'Give each provider a profile page worth reading',
    role: 'client',
    want: 'one page showing who this person is, what they have done and how they are rated',
    so: 'I can decide whether to contact them',
    ac: [
      'badges, portfolio, reviews and typical response time are shown',
      'nothing private or unverified is displayed',
    ],
  },
  'W3-T08': {
    title: 'Only show licensed professionals for regulated work',
    role: 'client',
    want: 'plumbing, gas and electrical results limited to verified professionals',
    so: 'I am not connected to someone unqualified for dangerous work',
    ac: [
      'regulated categories exclude unverified providers everywhere they appear',
      'losing verification removes the provider from those results immediately',
      'a test covers this specifically',
    ],
  },
  'W3-T09': {
    title: 'Let providers say when they are available',
    role: 'professional',
    want: 'to set my working hours and block days off',
    so: 'I am not contacted for times I cannot work',
    ac: ['weekly hours and blocked dates can be set', 'availability filters search results'],
  },

  // ---------------------------------------------------------------- W4 jobs & quotes
  'W4-T01': {
    title: 'Let clients post a job',
    role: 'client',
    want: 'to describe my problem once, with photos and a location',
    so: 'professionals understand what I need without a dozen questions',
    ac: [
      'description, photos, location, budget range and urgency can be submitted',
      'photos have location data stripped',
      'a draft can be saved and finished later',
    ],
  },
  'W4-T02': {
    title: 'Track a job through its life',
    role: 'client',
    want: 'to always know whether my job is open, awarded, in progress or finished',
    so: 'I am never left wondering what is happening',
    ac: [
      'the job moves through defined states only via allowed transitions',
      'every change is recorded',
      'the current state is obvious in the UI',
    ],
  },
  'W4-T03': {
    title: 'Let professionals send a quote',
    role: 'professional',
    want: 'to send a priced offer with a message and an expiry date',
    so: 'I can win work by explaining my price rather than racing to the bottom',
    ac: [
      'one active quote per professional per job — a second is rejected, not stacked',
      'quoting on a closed job is refused with a clear reason',
      'an unreasonable amount is rejected',
      'the client is notified',
    ],
  },
  'W4-T04': {
    title: 'Let clients compare quotes and choose one',
    role: 'client',
    want: 'to see the offers side by side and pick one',
    so: 'I choose on value rather than only on price',
    ac: [
      'quotes are listed with price, rating and response time',
      'the cheapest is never hidden',
      'accepting one closes the others and tells those professionals',
    ],
  },
  'W4-T05': {
    title: 'Turn an accepted quote into a booking',
    role: 'client',
    want: 'accepting a quote to create a confirmed job with payment attached',
    so: 'there is no gap between agreeing and being committed',
    ac: [
      'accepting creates a booking at the agreed amount',
      'payment is initiated immediately',
      'the job cannot be awarded twice',
    ],
  },
  'W4-T06': {
    title: 'Let clients and professionals message about a job',
    role: 'client',
    want: 'to ask questions in one place attached to the job',
    so: 'details are not lost across phone calls and texts',
    ac: [
      'messages and attachments are scoped to the job',
      'both sides are notified',
      'attachments follow the same safety rules as other uploads',
    ],
  },
  'W4-T07': {
    title: 'Show professionals the jobs they can actually do',
    role: 'professional',
    want: 'a feed of open jobs matching my trade and travel radius',
    so: 'I do not waste time reading jobs I cannot take',
    ac: [
      'only matching categories and locations are shown',
      'regulated jobs appear only for verified professionals',
      'jobs I already quoted are marked',
    ],
  },
  'W4-T08': {
    title: 'Keep the transaction on the platform until it is paid',
    role: 'platform owner',
    want: 'contact details hidden until a booking is paid',
    so: 'we are paid for the introductions we make',
    ac: [
      'phone numbers and emails are masked before payment',
      'they are revealed once payment succeeds',
      'attempts to share them in messages are handled per the agreed policy',
    ],
  },

  // ---------------------------------------------------------------- W5 money
  'W5-T01': {
    title: 'Let professionals get set up to be paid',
    role: 'professional',
    want: 'to connect my bank details and be verified once',
    so: 'money reaches me without paperwork on every job',
    ac: [
      'onboarding completes inside the product',
      'verification status is reflected on the profile',
      'an unverified provider cannot receive payouts',
    ],
  },
  'W5-T02': {
    title: 'Take payment for a booking',
    role: 'client',
    want: 'to pay for a job securely, with card authentication where required',
    so: 'I can hire someone in a couple of taps and know I am protected',
    ac: [
      'payment is taken for the agreed amount',
      'strong customer authentication is handled',
      'a failed payment leaves the booking clearly unpaid, never half-confirmed',
    ],
    note: 'Whether funds are held until completion depends on BD-01. Build the mechanism; do not assume the answer.',
  },
  'W5-T03': {
    title: 'Handle payment provider notifications reliably',
    role: 'developer',
    want: 'payment events processed exactly once, in any order',
    so: 'a duplicate or late notification never double-charges or double-pays anyone',
    ac: [
      'the same event delivered twice changes nothing the second time',
      'events arriving out of order are handled',
      'events that cannot be processed land somewhere visible rather than vanishing',
    ],
  },
  'W5-T04': {
    title: 'Pay the professional when the job is done',
    role: 'professional',
    want: 'to be paid promptly after completing the work, minus a clear commission',
    so: 'I trust the platform enough to keep using it',
    ac: [
      'completion releases payment to the professional',
      'the commission is deducted and recorded',
      'the professional can see what they were paid and why',
    ],
    note: 'The commission rate is BD-02. Read it from configuration.',
  },
  'W5-T05': {
    title: 'Handle cancellations and refunds',
    role: 'client',
    want: 'a clear outcome if I cancel, and my money back when I am entitled to it',
    so: 'booking does not feel risky',
    ac: [
      'refund amount follows the published policy bands',
      'partial refunds work',
      'both parties are told what happened and why',
    ],
    note: 'Policy bands are BD-04.',
  },
  'W5-T06': {
    title: 'Handle disputes without losing money',
    role: 'platform owner',
    want: 'to freeze a payout while a disagreement is resolved',
    so: 'we are not paying out money that may need to be returned',
    ac: [
      'a booking can be marked disputed and the payout held',
      'an operator can resolve it either way',
      'every action is recorded',
    ],
  },
  'W5-T07': {
    title: 'Sell subscriptions to professionals',
    role: 'professional',
    want: 'to upgrade my plan and change or cancel it later',
    so: 'I can pay for more visibility when it is worth it',
    ac: [
      'upgrade, downgrade and cancel all work with correct proration',
      'a failed renewal retries and then downgrades gracefully',
      'the current plan and renewal date are visible',
    ],
    note: 'Prices are BD-03.',
  },
  'W5-T08': {
    title: 'Make the subscription actually change what a professional gets',
    role: 'professional',
    want: 'my plan to visibly affect what I can do',
    so: 'paying is worth it',
    ac: [
      'entitlements are enforced consistently across quoting, radius and visibility',
      'downgrading removes them immediately',
      'hitting a limit explains which plan lifts it',
    ],
    note: 'What each tier grants is BD-03.',
  },
  'W5-T09': {
    title: 'Produce invoices and payout statements',
    role: 'professional',
    want: 'proper documents for the work I do and the fees I pay',
    so: 'my accounting is straightforward',
    ac: [
      'each completed job produces a compliant document',
      'tax is shown correctly',
      'statements can be downloaded',
    ],
    note: 'Blocked on BD-13 — an accountant defines the rules, not the code.',
  },
  'W5-T10': {
    title: 'Record every movement of money',
    role: 'platform owner',
    want: 'an internal ledger of every charge, fee, payout and refund',
    so: 'I can answer where any euro went without reading a payment dashboard',
    ac: [
      'every money movement writes a balanced ledger entry',
      'entries reference the payment provider’s own records',
      'the ledger cannot be edited after the fact',
    ],
  },
  'W5-T11': {
    title: 'Detect when our numbers stop matching',
    role: 'platform owner',
    want: 'an automatic comparison between our ledger and the payment provider',
    so: 'a discrepancy is caught in a day rather than at year end',
    ac: [
      'reconciliation runs on a schedule',
      'any mismatch raises an alert with enough detail to investigate',
    ],
  },

  // ---------------------------------------------------------------- W6 auctions
  'W6-T01': {
    title: 'Let clients open a job for competitive bidding',
    role: 'client',
    want: 'to invite offers with a deadline instead of picking someone straight away',
    so: 'I get a better price for a job that is not urgent',
    ac: [
      'an auction can be created from a job with a closing time',
      'sealed or open bidding can be chosen',
      'the rules are explained to both sides before it starts',
    ],
    note: 'Defaults are BD-09.',
  },
  'W6-T02': {
    title: 'Let professionals bid',
    role: 'professional',
    want: 'to place a competitive offer with a short message',
    so: 'I can win work I would not otherwise be shortlisted for',
    ac: [
      'one active bid per professional',
      'bids after closing are rejected',
      'my plan’s bid allowance is enforced',
      'in a sealed auction I cannot see anyone else’s bid',
    ],
  },
  'W6-T03': {
    title: 'Close auctions automatically and exactly once',
    role: 'client',
    want: 'the auction to close on time and award correctly without me watching it',
    so: 'I can post a job and come back to a decision',
    ac: [
      'closing happens on schedule',
      'a restart mid-close never awards twice',
      'an auction with no bids ends cleanly and tells the client what to do next',
    ],
  },
  'W6-T04': {
    title: 'Stop last-second sniping',
    role: 'professional',
    want: 'the deadline extended when someone bids at the last moment',
    so: 'winning depends on the offer rather than on network timing',
    ac: [
      'a late bid extends the closing time by the configured window',
      'the extension is visible to everyone',
    ],
    note: 'Window length is BD-09.',
  },
  'W6-T05': {
    title: 'Let clients award before the deadline',
    role: 'client',
    want: 'to accept a good offer without waiting for the auction to end',
    so: 'urgent work is not delayed by my own deadline',
    ac: [
      'the client can award early',
      'remaining bidders are told',
      'the auction closes immediately',
    ],
  },
  'W6-T06': {
    title: 'Show the auction clearly to both sides',
    role: 'client',
    want: 'to see time remaining and the offers I am allowed to see',
    so: 'I understand what is happening without reading rules',
    ac: [
      'countdown reflects server time',
      'sealed auctions reveal nothing they should not',
      'awarding is one obvious action',
    ],
  },
  'W6-T07': {
    title: 'Prevent auction abuse',
    role: 'professional',
    want: 'bidders who lowball and withdraw to be limited',
    so: 'honest bidding is not pointless',
    ac: [
      'retractions are limited and recorded',
      'implausible bids are flagged',
      'repeat offenders can be restricted',
    ],
    note: 'Thresholds are BD-09.',
  },

  // ---------------------------------------------------------------- W7 emergency
  'W7-T01': {
    title: 'Let clients raise an emergency',
    role: 'client',
    want: 'to request urgent help and understand the cost before confirming',
    so: 'I can act fast in a crisis without fearing the bill',
    ac: [
      'an urgent request can be raised in a few taps',
      'the pricing is shown before confirmation',
      'only regulated-capable professionals are contacted where required',
    ],
    note: 'Pricing model is BD-05.',
  },
  'W7-T02': {
    title: 'Alert nearby available professionals',
    role: 'client',
    want: 'my emergency sent to professionals close by who are available now',
    so: 'someone can actually come',
    ac: [
      'the request goes to nearby available professionals first',
      'the radius widens if nobody responds',
      'unverified providers are excluded from regulated work',
    ],
  },
  'W7-T03': {
    title: 'Make sure exactly one professional gets the job',
    role: 'professional',
    want: 'to know that accepting means the job is mine',
    so: 'I do not drive across town to find someone else took it',
    ac: [
      'only one acceptance can ever succeed',
      'the rest are told immediately and clearly',
      'proven by a test firing many simultaneous acceptances',
    ],
  },
  'W7-T04': {
    title: 'Reach professionals wherever they are',
    role: 'professional',
    want: 'to be notified by push, email or SMS',
    so: 'urgent work reaches me when the app is closed',
    ac: [
      'notifications are delivered through the available channels',
      'a failed channel falls back to another',
      'notifications stop once the job is taken',
    ],
  },
  'W7-T05': {
    title: 'Let professionals say they are available right now',
    role: 'professional',
    want: 'a switch for being open to emergencies',
    so: 'I am not woken at 4am on a day off',
    ac: [
      'availability can be turned on and off instantly',
      'it expires automatically instead of staying on forever',
    ],
  },
  'W7-T06': {
    title: 'Handle nobody accepting',
    role: 'client',
    want: 'to be told honestly when no one is available and offered another route',
    so: 'I am not left staring at a spinner during an emergency',
    ac: [
      'the search widens, then stops with a clear message',
      'the client is offered the quote flow as an alternative',
      'no false promises about response times are made',
    ],
  },
  'W7-T07': {
    title: 'Show the client what is happening',
    role: 'client',
    want: 'to see that someone accepted and is on the way',
    so: 'I can stop worrying and prepare',
    ac: [
      'status updates from accepted to arrived are visible',
      'the professional’s name and rating are shown once accepted',
    ],
  },

  // ---------------------------------------------------------------- W8 trust
  'W8-T01': {
    title: 'Let professionals upload their licence',
    role: 'professional',
    want: 'to submit my certification securely',
    so: 'I can be verified and take on regulated work',
    ac: [
      'documents upload to private storage, never public',
      'files are scanned and location data stripped',
      'access is short-lived and logged',
    ],
  },
  'W8-T02': {
    title: 'Give operators a queue for checking licences',
    role: 'admin',
    want: 'to review submitted documents and approve or reject them with a reason',
    so: 'verification is fast, consistent and explainable',
    ac: [
      'pending submissions are listed with the document viewable',
      'approve and reject both require a note',
      'the professional is told the outcome',
    ],
  },
  'W8-T03': {
    title: 'Handle licences that expire',
    role: 'client',
    want: 'a verified badge to mean the licence is still valid today',
    so: 'the badge is worth trusting',
    ac: [
      'expiry is tracked and the professional reminded in advance',
      'an expired licence removes the badge and the regulated categories automatically',
    ],
  },
  'W8-T04': {
    title: 'Award badges that mean something',
    role: 'client',
    want: 'badges based on real behaviour rather than payment alone',
    so: 'I can shortlist quickly and correctly',
    ac: [
      'each badge has a documented rule',
      'badges are granted and removed automatically as behaviour changes',
      'a paid badge is visibly different from an earned one',
    ],
    note: 'Qualifying rules are BD-10.',
  },
  'W8-T05': {
    title: 'Let both sides review each other after a job',
    role: 'client',
    want: 'to rate the professional after the work is done',
    so: 'the next client benefits from my experience',
    ac: [
      'reviews are only possible after a completed, paid booking',
      'both directions are supported',
      'there is a short edit window, then it is final',
    ],
  },
  'W8-T06': {
    title: 'Show ratings honestly',
    role: 'client',
    want: 'averages that are not distorted by one or two reviews',
    so: 'I am not misled by a single five-star rating',
    ac: [
      'an average appears only above a minimum number of reviews',
      'the count is always shown alongside',
      'new providers are labelled as new rather than as unrated',
    ],
    note: 'The minimum is BD-10.',
  },
  'W8-T07': {
    title: 'Let people report content and have it reviewed',
    role: 'client',
    want: 'to flag an abusive review or fake portfolio',
    so: 'the platform stays trustworthy',
    ac: [
      'reporting is possible from the content itself',
      'operators can hide or remove with a recorded reason',
      'the author can appeal',
    ],
  },

  // ---------------------------------------------------------------- W9 admin
  'W9-T01': {
    title: 'Give operators a secure back office',
    role: 'admin',
    want: 'a separate admin login with everything I do recorded',
    so: 'privileged access is controlled and reviewable',
    ac: [
      'admin access is a distinct role, not a flag on a normal account',
      'every action is logged with before and after',
      'even views of sensitive data are recorded',
    ],
  },
  'W9-T02': {
    title: 'Let support find users and help them',
    role: 'admin',
    want: 'to search users and, where allowed, see what they see',
    so: 'I can resolve a complaint without a long back-and-forth',
    ac: [
      'user search works across the relevant fields',
      'impersonation follows the agreed policy: time-limited, visibly flagged, logged',
    ],
    note: 'Blocked on BD-11 — a privacy decision, not a technical one.',
  },
  'W9-T03': {
    title: 'Give operators a way to resolve money problems',
    role: 'admin',
    want: 'to refund, release or hold a payment from one screen',
    so: 'a stuck payment is resolved in minutes',
    ac: [
      'refunds and payout releases can be triggered with a reason',
      'every action is recorded and reversible where possible',
      'the money slice performs the movement, not the console',
    ],
  },
  'W9-T04': {
    title: 'Give operators a moderation queue',
    role: 'admin',
    want: 'reported content in one list to work through',
    so: 'reports do not sit unseen',
    ac: ['reports are queued with context', 'decisions are recorded and the reporter informed'],
  },
  'W9-T05': {
    title: 'Show how the marketplace is doing',
    role: 'platform owner',
    want: 'the numbers that matter on one page',
    so: 'I can tell whether this is working',
    ac: [
      'transaction volume, commission, active professionals and conversion per flow are shown',
      'payout health is visible',
      'numbers agree with the ledger',
    ],
  },
  'W9-T06': {
    title: 'Show how well the agents are working',
    role: 'platform owner',
    want: 'to see where agents get rejected and why',
    so: 'I can fix the prompts and specs instead of guessing',
    ac: [
      'interventions summarised by agent, cause and slice',
      'trends over time are visible',
      'it reads honestly even when the numbers are bad',
    ],
  },

  // ---------------------------------------------------------------- W10 quality & launch
  'W10-T01': {
    title: 'Create a believable demo marketplace',
    role: 'platform owner',
    want: 'staging filled with realistic professionals, listings and jobs',
    so: 'I can show the product and test flows that need existing data',
    ac: [
      'seed produces providers, listings and jobs in every state',
      'the data looks Spanish and plausible',
      'it is deterministic and rerunnable',
    ],
  },
  'W10-T02': {
    title: 'Test the critical journeys end to end',
    role: 'reviewer',
    want: 'automated tests that walk through each real user journey',
    so: 'we know the product works, not just that the units do',
    ac: [
      'each core journey is covered end to end',
      'tests run against a deployed preview',
      'a failure blocks the merge',
    ],
  },
  'W10-T03': {
    title: 'Test the payment failure paths',
    role: 'platform owner',
    want: 'declines, disputes, refunds and retries all exercised',
    so: 'the first real failure is not the first time we see it',
    ac: [
      'each failure scenario has a test',
      'duplicate and out-of-order notifications are covered',
    ],
  },
  'W10-T04': {
    title: 'Check the system holds up under load',
    role: 'developer',
    want: 'search and emergency broadcast tested at realistic volume',
    so: 'launch day is not the load test',
    ac: [
      'search stays responsive under expected peak',
      'a broadcast to many professionals completes in time',
      'results are recorded as a baseline',
    ],
  },
  'W10-T05': {
    title: 'Make the product usable for everyone',
    role: 'client',
    want: 'to use the site with a keyboard or a screen reader',
    so: 'a disability does not stop me getting a plumber',
    ac: [
      'core journeys pass an accessibility audit',
      'everything is reachable by keyboard with visible focus',
      'errors are announced, not only coloured',
    ],
  },
  'W10-T06': {
    title: 'Review the platform for security holes',
    role: 'platform owner',
    want: 'a deliberate check for the common ways this kind of platform is broken',
    so: 'we find the problems before someone else does',
    ac: [
      'every id-based endpoint is checked for access control',
      'uploads, authentication and input validation reviewed',
      'findings are fixed or explicitly accepted',
    ],
  },
  'W10-T07': {
    title: 'Publish the legal pages',
    role: 'platform owner',
    want: 'terms, privacy policy and cookie consent that reflect what we actually do',
    so: 'we can operate lawfully and honestly',
    ac: [
      'documents drafted by someone qualified',
      'consent is captured and recorded',
      'the platform’s role and liability are stated plainly',
    ],
    note: 'Lawyer-drafted. Agents wire up the text, they do not write it.',
  },
  'W10-T08': {
    title: 'Write the runbooks for when things break',
    role: 'developer',
    want: 'written procedures for payout failures, provider outages and rollbacks',
    so: 'an incident at 2am is followed, not invented',
    ac: [
      'a runbook per likely failure',
      'a rollback procedure that has actually been rehearsed',
      'a tested backup restore',
    ],
  },
  'W10-T09': {
    title: 'Prepare the beta launch',
    role: 'platform owner',
    want: 'a checklist and a way back if it goes wrong',
    so: 'launching is a decision rather than a leap',
    ac: [
      'pre-launch checklist completed',
      'rollback plan written and rehearsed',
      'a go/no-go decision is recorded',
    ],
  },
};
